name: Code Score

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  score:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Calculate code score
        id: score
        run: |
          score=$(python main_sonarqube.py ${{ github.sha }})
          echo "::set-output name=score::$score"

      - name: Create status check
        uses: actions/github-script@v5
        with:
          script: |
            const { context, github } = require('@actions/github');
            const score = '${{ steps.score.outputs.score }}';
            github.repos.createCommitStatus({
              ...context.repo,
              sha: context.sha,
              state: 'success',
              description: `Code score: ${score}`,
              context: 'Code Score'
            });
