name: SonarQube Analysis

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify your Python version

      - name: Upgrade pip and setuptools
        run: |
          python -m pip install --upgrade pip setuptools

      - name: Install dependencies
        run: |
          python -m pip install requests==2.28.1
          python -m pip install PyYAML==6.0

      - name: Verify installation
        run: |
          python -c "import requests; print(requests.__version__)"
          python -c "import yaml; print(yaml.__version__)"

      - name: Run SonarQube analysis
        run: python main_sonarqube.py 

      - name: Upload SonarQube results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: './sonarqube-report.sarif'
