name: Post Commit Score

on:
  push:
    branches:
      - main

jobs:
  post-score:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Calculate score
        id: calculate-score
        run: |
          SCORE=$(shuf -i 0-100 -n 1)
          echo "SCORE=$SCORE" >> $GITHUB_ENV
          echo "Commit Score: $SCORE"

      - name: Update commit status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d "{\"state\": \"success\", \"description\": \"Commit Score: ${{ env.SCORE }}\", \"context\": \"commit-score\"}"
